# Generated by Django 3.2.5 on 2021-12-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blango', '0004_auto_20211227_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
